# Generated by Django 2.1.3 on 2019-01-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animalid', models.AutoField(db_column='AnimalID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('edad', models.IntegerField(db_column='Edad')),
                ('raza', models.CharField(db_column='Raza', max_length=40)),
                ('genero', models.BooleanField(db_column='Genero')),
                ('descripicon', models.CharField(db_column='Descripicon', max_length=300)),
                ('estado', models.BooleanField(db_column='Estado')),
                ('foto', models.BinaryField(db_column='Foto')),
            ],
            options={
                'db_table': 'Animal',
            },
        ),
        migrations.CreateModel(
            name='Detalleinteres',
            fields=[
                ('detalleid', models.AutoField(db_column='DetalleID', primary_key=True, serialize=False)),
                ('descripcionadicional', models.CharField(db_column='DescripcionAdicional', max_length=300)),
                ('fechasolicitud', models.DateField(db_column='FechaSolicitud')),
                ('fechafinal', models.DateField(blank=True, db_column='FechaFinal', null=True)),
                ('estado', models.CharField(db_column='Estado', max_length=10)),
            ],
            options={
                'db_table': 'detalleinteres',
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('encargadoid', models.AutoField(db_column='EncargadoID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('apellido', models.CharField(db_column='Apellido', max_length=30)),
                ('direccion', models.CharField(db_column='Direccion', max_length=300)),
                ('telefono', models.CharField(db_column='Telefono', max_length=30)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'encargado',
            },
        ),
        migrations.CreateModel(
            name='Solicitudinteres',
            fields=[
                ('idsolicitudinteres', models.AutoField(db_column='IDsolicitudInteres', primary_key=True, serialize=False)),
                ('telefono', models.CharField(db_column='Telefono', max_length=24)),
                ('animalid', models.ForeignKey(db_column='AnimalID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Animal')),
                ('detalleid', models.ForeignKey(db_column='DetalleID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Detalleinteres')),
            ],
            options={
                'db_table': 'SolicitudInteres',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioid', models.AutoField(db_column='UsuarioID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('apellido', models.CharField(db_column='Apellido', max_length=40)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=60)),
                ('nombreusuario', models.CharField(db_column='NombreUsuario', max_length=60)),
                ('correo', models.CharField(db_column='Correo', max_length=200)),
                ('genero', models.IntegerField(db_column='Genero')),
                ('adminstatus', models.BooleanField(db_column='AdminStatus')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='solicitudinteres',
            name='usuarioid',
            field=models.ForeignKey(db_column='UsuarioID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='animal',
            name='encargado',
            field=models.ForeignKey(db_column='Encargado', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Encargado'),
        ),
    ]
