# Generated by Django 2.1.3 on 2019-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='foto',
        ),
        migrations.AddField(
            model_name='animal',
            name='image_file',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
        migrations.AlterModelTable(
            name='solicitudinteres',
            table='solicitudinteres',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
