# Generated by Django 2.1.3 on 2019-01-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190117_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image_file',
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.TextField(db_column='Foto', default='null'),
        ),
    ]
