# Generated by Django 2.1.3 on 2019-01-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190118_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.CharField(db_column='Foto', max_length=300),
        ),
    ]
